### ISSUE TITLE
Add BitWarden

### ISSUE THREAD

**Issue by taylorj14atwit** [Politiwatch/privacyspy#179] opened 2023-11-17 02:11 UTC
**What's the product you'd like PrivacySpy to add?**
BitWarden claims to be the leader in password management software. Even though their main product is open-source, analyzing the way that BitWarden handles data hosted by their own servers (which is their main business) would be beneficial.

**Where is the product's privacy policy? (Give a URL.)**
https://bitwarden.com/privacy/

**Have you considered adding this product yourself?**
Yes, but I have little to no experience with Git and I would not be the best to provide this information.

**Comment by doamatto** [comment] 2023-11-17 04:41
Dupe of #173. Will close with PR.

**Closed as completed** 2024-09-09 17:01 UTC
